[unstable]
build-std = ['core', 'compiler_builtins']
build-std-features = ["compiler-builtins-mem"]

[build]
target = './target-config/x86_64-lilith.json'

[target.'cfg(target_os = "none")']
runner = "bootimage runner"